export enum UnitMeasurements {
    PIECE = "Pieza",
    BUNCH = "Manojo",
    GRAM = "Gramo",
    KILOGRAM = "Kilogramo",
    POUND = "Libra",
    OUNCE = "Onza",
    LITER = "Litro",
    MILLILITER = "Mililitro",
    PINT = "Pinta",
    QUART = "Cuarto",
    GALLON = "Galon",
    MILLIMETER = "Milímetro",
    CENTIMETER = "Centímetro",
    METER = "Metro",
    INCH = "Pulgada",
    FOOT = "Pie",
}